# Generated by Django 3.2.7 on 2021-09-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_video_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
