# Generated by Django 3.2.7 on 2021-09-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0002_alter_replies_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='video_id',
            field=models.CharField(max_length=100),
        ),
    ]
