# Generated by Django 3.2.7 on 2021-09-17 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_delete_reply'),
        ('replies', '0003_alter_replies_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
    ]
